version: '3.4'

services:
  graphapi:
    image: ${DOCKER_REGISTRY}graphapi
    build:
      context: .
      dockerfile: GraphAPI/Dockerfile
  musicstore:
    image: ${DOCKER_REGISTRY}musicstore
    build:
      context: .
      dockerfile: MusicStore/Dockerfile
    depends_on:
      - db
  db:
    image: microsoft/mssql-server-linux