version: "3"

services:
  api:
    build: .
    environment:
      - DB_CONNECTION_STRING=Server=db;Database=music-store;User=sa;Password=ch0r1z0n!;
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: microsoft/mssql-server-linux
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=ch0r1z0n!"
    ports:
      - "1433:1433"