version: "3"
services:
  api:
    build: .
    environment:
      - DB_CONNECTION_STRING=Server=db;Database=music-store;User=sa;Password=mssqlServer1433;
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: microsoft/mssql-server-linux
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=mssqlServer1433"
    ports:
      - "1433:1433"